Update host-updater

diff --git a/packages/packages_local/hosts-updater/src/hosts-updater b/packages/packages_local/hosts-updater/src/hosts-updater
--- a/packages/packages_local/hosts-updater/src/hosts-updater
+++ b/packages/packages_local/hosts-updater/src/hosts-updater
@@ -3,13 +3,25 @@
 # Update the host file with the curated list from
 # https://github.com/StevenBlack/hosts
 
+# Get hosts files
 while true; do
     hosts=$(curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts)
-    [[ $? == 0 ]] && echo "$hosts" > /etc/hosts && break
-    echo "Updating hosts file from online failed... sleeping for 1mn"
-    sleep 60
+    err1=$?
+    hosts_google=$(curl https://gist.githubusercontent.com/unixb0y/4973fece2d5099bd53143a18a54318f3/raw/3254ebe6ebfcf1c9549d39999ed8f5e98e30e4da/hosts)
+    err2=$?
+    if [[ $err1 == 0 || $err2 == 0 ]] ; then
+        break
+    else
+        echo "Updating hosts file from online failed... sleeping for 1mn"
+        sleep 60
+    fi
 done
 
-# remove reddit and add 9gag
+# Overwrite hosts file
+echo "$hosts" > /etc/hosts
+echo "$hosts_google" >> /etc/hosts
+
+# remove reddit and youtube
 sed -i '/^.*reddit.*$/ d' /etc/hosts
-echo "0.0.0.0 9gag.com" >> /etc/hosts
+sed -i '/^.* www.youtube.com .*$/ d' /etc/hosts
+sed -i '/^.* youtube.com .*$/ d' /etc/hosts
