Update host-updater

diff --git a/packages/packages_local/hosts-updater/src/hosts-updater b/packages/packages_local/hosts-updater/src/hosts-updater
--- a/packages/packages_local/hosts-updater/src/hosts-updater
+++ b/packages/packages_local/hosts-updater/src/hosts-updater
@@ -3,5 +3,9 @@
 # Update the host file with the curated list from
 # https://github.com/StevenBlack/hosts
 
-#
-curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts > /etc/hosts
+while true; do
+    hosts=$(curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts)	
+    [[ $? == 0 ]] && echo "$hosts" > /etc/hosts && break
+    echo "Updating hosts file from online failed... sleeping for 1mn"
+    sleep 60
+done
